-- Outbox Pattern table (RabbitMQ-specific schema matching Issue 4)
CREATE TABLE outbox_messages (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id       VARCHAR(36) UNIQUE NOT NULL,  -- UUID for deduplication
    exchange         VARCHAR(255) NOT NULL,
    routing_key      VARCHAR(255) NOT NULL,
    event_type       VARCHAR(512) NOT NULL,        -- Fully qualified class name
    payload          TEXT NOT NULL,                -- JSON string (Jackson serialized)
    status           VARCHAR(50) NOT NULL DEFAULT 'PENDING',  -- PENDING, PUBLISHED, FAILED
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at     TIMESTAMP NULL,
    CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
);

CREATE INDEX idx_outbox_status ON outbox_messages(status);
CREATE INDEX idx_outbox_created_at ON outbox_messages(created_at);
CREATE UNIQUE INDEX idx_outbox_message_id ON outbox_messages(message_id);

-- Optimistic Locking: Add version column to shared entities
ALTER TABLE users ADD COLUMN version BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE challenge ADD COLUMN version BIGINT DEFAULT 0 NOT NULL;
