-- GitHub Organization 등록 기능 — 조직 저장소 테이블
-- visibility: public / private
-- is_active: 수집 대상 여부
CREATE TABLE organization_repositories
(
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    created_at           TIMESTAMP    NOT NULL,
    updated_at           TIMESTAMP    NOT NULL,
    organization_id      BIGINT       NOT NULL,
    github_repo_id       BIGINT       NOT NULL,
    repository_name      VARCHAR(255) NOT NULL,
    repository_full_name VARCHAR(255) NOT NULL,
    repository_url       VARCHAR(500) NOT NULL,
    visibility           VARCHAR(20)  NOT NULL,
    is_active            BOOLEAN      NOT NULL DEFAULT TRUE,
    synced_at            TIMESTAMP    NOT NULL,
    CONSTRAINT pk_organization_repositories PRIMARY KEY (id),
    CONSTRAINT uc_organization_repositories_github_repo_id UNIQUE (github_repo_id),
    CONSTRAINT fk_organization_repositories_on_org FOREIGN KEY (organization_id) REFERENCES organizations (id)
);
