-- ============================================
-- Core User & Auth Tables
-- ============================================

CREATE TABLE github_user (
    github_id          BIGINT       NOT NULL,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL,
    github_login       VARCHAR(255),
    github_name        VARCHAR(255),
    github_avatar_url  VARCHAR(255),
    github_token       TEXT,
    last_crawling      TIMESTAMP,
    CONSTRAINT pk_github_user PRIMARY KEY (github_id)
);

CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    name         VARCHAR(50)  NOT NULL,
    kut_id       VARCHAR(255) NOT NULL,
    kut_email    VARCHAR(255) NOT NULL,
    password     VARCHAR(255) NOT NULL,
    introduction VARCHAR(255),
    github_id    BIGINT       NOT NULL,
    is_deleted   BOOLEAN      NOT NULL DEFAULT FALSE,
    point        INT          NOT NULL DEFAULT 0,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_github UNIQUE (github_id),
    CONSTRAINT uc_users_kut UNIQUE (kut_id),
    CONSTRAINT uc_users_kut_email UNIQUE (kut_email),
    CONSTRAINT fk_users_on_github FOREIGN KEY (github_id) REFERENCES github_user (github_id)
);

CREATE TABLE permission (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_permission PRIMARY KEY (id),
    CONSTRAINT uc_permission_name UNIQUE (name)
);

CREATE TABLE policy (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_policy PRIMARY KEY (id),
    CONSTRAINT uc_policy_name UNIQUE (name)
);

CREATE TABLE role (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,
    name             VARCHAR(255) NOT NULL,
    description      VARCHAR(255),
    can_access_admin BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_role PRIMARY KEY (id),
    CONSTRAINT uc_role_name UNIQUE (name)
);

CREATE TABLE policy_permission (
    policy_id     BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_policy_permission PRIMARY KEY (policy_id, permission_id),
    CONSTRAINT fk_policy_permission_on_policy FOREIGN KEY (policy_id) REFERENCES policy (id),
    CONSTRAINT fk_policy_permission_on_permission FOREIGN KEY (permission_id) REFERENCES permission (id)
);

CREATE TABLE role_policy (
    role_id   BIGINT NOT NULL,
    policy_id BIGINT NOT NULL,
    CONSTRAINT pk_role_policy PRIMARY KEY (role_id, policy_id),
    CONSTRAINT fk_role_policy_on_role FOREIGN KEY (role_id) REFERENCES role (id),
    CONSTRAINT fk_role_policy_on_policy FOREIGN KEY (policy_id) REFERENCES policy (id)
);

CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_role_on_role FOREIGN KEY (role_id) REFERENCES role (id)
);

-- ============================================
-- Community Tables
-- ============================================

CREATE TABLE board (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at         TIMESTAMP   NOT NULL,
    updated_at         TIMESTAMP   NOT NULL,
    name               VARCHAR(30) NOT NULL,
    description        VARCHAR(255) NOT NULL,
    is_recruit_allowed BOOLEAN     NOT NULL DEFAULT FALSE,
    is_notice          BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_board PRIMARY KEY (id)
);

CREATE TABLE team (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(255) NOT NULL,
    image_url   VARCHAR(255),
    CONSTRAINT pk_team PRIMARY KEY (id)
);

CREATE TABLE team_member (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    team_id    BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    role       VARCHAR(255) NOT NULL,
    CONSTRAINT pk_team_member PRIMARY KEY (id),
    CONSTRAINT fk_team_member_on_team FOREIGN KEY (team_id) REFERENCES team (id),
    CONSTRAINT fk_team_member_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE team_invite (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    team_id     BIGINT    NOT NULL,
    inviter_id  BIGINT    NOT NULL,
    invitee_id  BIGINT    NOT NULL,
    expires_at  TIMESTAMP NOT NULL,
    CONSTRAINT pk_team_invite PRIMARY KEY (id),
    CONSTRAINT uk_team_invite_team_invitee UNIQUE (team_id, invitee_id),
    CONSTRAINT fk_team_invite_on_team FOREIGN KEY (team_id) REFERENCES team (id),
    CONSTRAINT fk_team_invite_on_inviter FOREIGN KEY (inviter_id) REFERENCES users (id),
    CONSTRAINT fk_team_invite_on_invitee FOREIGN KEY (invitee_id) REFERENCES users (id)
);

CREATE TABLE article (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL,
    board_id       BIGINT       NOT NULL,
    author_id      BIGINT       NOT NULL,
    dtype          VARCHAR(31)  NOT NULL,
    title          VARCHAR(255) NOT NULL,
    content        TEXT         NOT NULL,
    views          INT          NOT NULL DEFAULT 0,
    likes          INT          NOT NULL DEFAULT 0,
    comments_count INT          NOT NULL DEFAULT 0,
    is_deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_pinned      BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_article PRIMARY KEY (id),
    CONSTRAINT fk_article_on_board FOREIGN KEY (board_id) REFERENCES board (id),
    CONSTRAINT fk_article_on_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE article_tags (
    article_id BIGINT       NOT NULL,
    tag        VARCHAR(255),
    CONSTRAINT fk_article_tags_on_article FOREIGN KEY (article_id) REFERENCES article (id)
);

CREATE TABLE article_like (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    user_id    BIGINT    NOT NULL,
    article_id BIGINT    NOT NULL,
    CONSTRAINT pk_article_like PRIMARY KEY (id),
    CONSTRAINT fk_article_like_on_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_article_like_on_article FOREIGN KEY (article_id) REFERENCES article (id)
);

CREATE TABLE article_bookmark (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    user_id    BIGINT    NOT NULL,
    article_id BIGINT    NOT NULL,
    CONSTRAINT pk_article_bookmark PRIMARY KEY (id),
    CONSTRAINT fk_article_bookmark_on_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_article_bookmark_on_article FOREIGN KEY (article_id) REFERENCES article (id)
);

CREATE TABLE comment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    article_id BIGINT    NOT NULL,
    author_id  BIGINT    NOT NULL,
    content    TEXT      NOT NULL,
    likes      INT       NOT NULL DEFAULT 0,
    is_deleted BOOLEAN   NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT fk_comment_on_article FOREIGN KEY (article_id) REFERENCES article (id),
    CONSTRAINT fk_comment_on_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE INDEX idx_comment_is_deleted ON comment(is_deleted);
CREATE INDEX idx_comment_article_deleted ON comment(article_id, is_deleted);

CREATE TABLE comment_like (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    user_id    BIGINT    NOT NULL,
    comment_id BIGINT    NOT NULL,
    CONSTRAINT pk_comment_like PRIMARY KEY (id),
    CONSTRAINT fk_comment_like_on_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_comment_like_on_comment FOREIGN KEY (comment_id) REFERENCES comment (id)
);

CREATE TABLE recruit (
    id         BIGINT       NOT NULL,
    team_id    BIGINT       NOT NULL,
    status     VARCHAR(255) NOT NULL,
    start_date TIMESTAMP    NOT NULL,
    end_date   TIMESTAMP,
    CONSTRAINT pk_recruit PRIMARY KEY (id),
    CONSTRAINT fk_recruit_on_article FOREIGN KEY (id) REFERENCES article (id),
    CONSTRAINT fk_recruit_on_team FOREIGN KEY (team_id) REFERENCES team (id)
);

CREATE TABLE recruit_apply (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    recruit_id    BIGINT       NOT NULL,
    user_id       BIGINT       NOT NULL,
    status        VARCHAR(255) NOT NULL,
    reason        VARCHAR(255) NOT NULL,
    portfolio_url VARCHAR(255),
    CONSTRAINT pk_recruit_apply PRIMARY KEY (id),
    CONSTRAINT fk_recruit_apply_on_recruit FOREIGN KEY (recruit_id) REFERENCES recruit (id),
    CONSTRAINT fk_recruit_apply_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ============================================
-- Attachment & Report Tables
-- ============================================

CREATE TABLE attachment (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    stored_file_name   VARCHAR(255) NOT NULL UNIQUE,
    file_size          BIGINT       NOT NULL,
    content_type       VARCHAR(100),
    url                VARCHAR(500) NOT NULL,
    article_id         BIGINT,
    uploaded_by        BIGINT       NOT NULL,
    uploaded_at        TIMESTAMP    NOT NULL,
    CONSTRAINT pk_attachment PRIMARY KEY (id),
    CONSTRAINT fk_attachment_on_article FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE CASCADE,
    CONSTRAINT fk_attachment_on_uploader FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

CREATE INDEX idx_attachment_article ON attachment(article_id);
CREATE INDEX idx_attachment_uploader ON attachment(uploaded_by);

CREATE TABLE report (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    reporter_id  BIGINT       NOT NULL,
    target_type  VARCHAR(255) NOT NULL,
    target_id    BIGINT       NOT NULL,
    reason       VARCHAR(255) NOT NULL,
    description  TEXT,
    status       VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP,
    CONSTRAINT pk_report PRIMARY KEY (id),
    CONSTRAINT fk_report_on_reporter FOREIGN KEY (reporter_id) REFERENCES users (id)
);

-- ============================================
-- Challenge & Point System
-- ============================================

CREATE TABLE challenge (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    "condition" TEXT         NOT NULL,
    tier        INT          NOT NULL,
    image_url   VARCHAR(255),
    point       INT          NOT NULL,
    CONSTRAINT pk_challenge PRIMARY KEY (id)
);

CREATE TABLE challenge_history (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at              TIMESTAMP NOT NULL,
    updated_at              TIMESTAMP NOT NULL,
    user_id                 BIGINT    NOT NULL,
    challenge_id            BIGINT    NOT NULL,
    is_achieved             BOOLEAN   NOT NULL DEFAULT FALSE,
    achieved_at             TIMESTAMP,
    progress_at_achievement INT       DEFAULT 100,
    CONSTRAINT pk_challenge_history PRIMARY KEY (id),
    CONSTRAINT fk_challenge_history_on_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_challenge_history_on_challenge FOREIGN KEY (challenge_id) REFERENCES challenge (id)
);

CREATE TABLE point_transactions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    user_id       BIGINT       NOT NULL,
    amount        INT          NOT NULL,
    type          VARCHAR(20)  NOT NULL,
    source        VARCHAR(20)  NOT NULL,
    reason        VARCHAR(255) NOT NULL,
    balance_after INT          NOT NULL,
    CONSTRAINT pk_point_transactions PRIMARY KEY (id),
    CONSTRAINT fk_point_transactions_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_point_transactions_user ON point_transactions (user_id);
CREATE INDEX idx_point_transactions_created_at ON point_transactions (created_at DESC);

-- ============================================
-- Notification & Admin Tables
-- ============================================

CREATE TABLE notification (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id      BIGINT       NOT NULL,
    type         VARCHAR(50)  NOT NULL,
    title        VARCHAR(255) NOT NULL,
    message      TEXT         NOT NULL,
    reference_id BIGINT,
    is_read      BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_notification PRIMARY KEY (id),
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_notification_user_created ON notification(user_id, created_at DESC);
CREATE INDEX idx_notification_user_unread ON notification(user_id, is_read);

CREATE TABLE banner_setting (
    id        BIGINT  PRIMARY KEY DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT banner_setting_singleton CHECK (id = 1)
);

INSERT INTO banner_setting (id, is_active) VALUES (1, FALSE) ON CONFLICT DO NOTHING;

-- ============================================
-- GitHub Statistics Tables
-- ============================================

CREATE TABLE github_user_statistics (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    github_id                VARCHAR(100) NOT NULL UNIQUE,
    total_commits            INT          NOT NULL DEFAULT 0,
    total_lines              INT          NOT NULL DEFAULT 0,
    total_additions          INT          NOT NULL DEFAULT 0,
    total_deletions          INT          NOT NULL DEFAULT 0,
    total_prs                INT          NOT NULL DEFAULT 0,
    total_issues             INT          NOT NULL DEFAULT 0,
    owned_repos_count        INT          NOT NULL DEFAULT 0,
    contributed_repos_count  INT          NOT NULL DEFAULT 0,
    total_stars_received     INT          NOT NULL DEFAULT 0,
    total_forks_received     INT          NOT NULL DEFAULT 0,
    night_commits            INT          NOT NULL DEFAULT 0,
    day_commits              INT          NOT NULL DEFAULT 0,
    activity_score           DECIMAL(10, 2) NOT NULL DEFAULT 0,
    diversity_score          DECIMAL(10, 2) NOT NULL DEFAULT 0,
    impact_score             DECIMAL(10, 2) NOT NULL DEFAULT 0,
    total_score              DECIMAL(10, 2) NOT NULL DEFAULT 0,
    calculated_at            TIMESTAMP    NOT NULL,
    data_period_start        DATE,
    data_period_end          DATE,
    CONSTRAINT pk_github_user_statistics PRIMARY KEY (id)
);

CREATE INDEX idx_gus_github_id ON github_user_statistics (github_id);
CREATE INDEX idx_gus_total_score ON github_user_statistics (total_score DESC);
CREATE INDEX idx_gus_calculated_at ON github_user_statistics (calculated_at);

CREATE TABLE github_monthly_statistics (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    github_id                VARCHAR(100) NOT NULL,
    year                     INT          NOT NULL,
    month                    INT          NOT NULL,
    commits_count            INT          NOT NULL DEFAULT 0,
    lines_count              INT          NOT NULL DEFAULT 0,
    additions_count          INT          NOT NULL DEFAULT 0,
    deletions_count          INT          NOT NULL DEFAULT 0,
    prs_count                INT          NOT NULL DEFAULT 0,
    issues_count             INT          NOT NULL DEFAULT 0,
    created_repos_count      INT          NOT NULL DEFAULT 0,
    contributed_repos_count  INT          NOT NULL DEFAULT 0,
    calculated_at            TIMESTAMP    NOT NULL,
    CONSTRAINT pk_github_monthly_statistics PRIMARY KEY (id),
    CONSTRAINT uk_user_month UNIQUE (github_id, year, month)
);

CREATE INDEX idx_gms_github_id ON github_monthly_statistics (github_id);
CREATE INDEX idx_gms_year_month ON github_monthly_statistics (year, month);

CREATE TABLE github_repository_statistics (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    repo_owner              VARCHAR(100) NOT NULL,
    repo_name               VARCHAR(200) NOT NULL,
    contributor_github_id   VARCHAR(100) NOT NULL,
    stargazers_count        INT          NOT NULL DEFAULT 0,
    forks_count             INT          NOT NULL DEFAULT 0,
    watchers_count          INT          NOT NULL DEFAULT 0,
    is_owned                BOOLEAN      NOT NULL DEFAULT FALSE,
    total_commits_count     INT          NOT NULL DEFAULT 0,
    total_prs_count         INT          NOT NULL DEFAULT 0,
    total_issues_count      INT          NOT NULL DEFAULT 0,
    user_commits_count      INT          NOT NULL DEFAULT 0,
    user_prs_count          INT          NOT NULL DEFAULT 0,
    user_issues_count       INT          NOT NULL DEFAULT 0,
    last_commit_date        TIMESTAMP,
    description             VARCHAR(500),
    primary_language        VARCHAR(50),
    repo_created_at         TIMESTAMP,
    calculated_at           TIMESTAMP    NOT NULL,
    CONSTRAINT pk_github_repository_statistics PRIMARY KEY (id),
    CONSTRAINT uk_repo_contributor UNIQUE (repo_owner, repo_name, contributor_github_id)
);

CREATE INDEX idx_grs_contributor ON github_repository_statistics (contributor_github_id);
CREATE INDEX idx_grs_last_commit ON github_repository_statistics (last_commit_date DESC);
CREATE INDEX idx_grs_stars ON github_repository_statistics (stargazers_count DESC);

CREATE TABLE github_yearly_statistics (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    github_id        VARCHAR(100)   NOT NULL,
    year             INT            NOT NULL,
    commits          INT            NOT NULL DEFAULT 0,
    lines            INT            NOT NULL DEFAULT 0,
    additions        INT            NOT NULL DEFAULT 0,
    deletions        INT            NOT NULL DEFAULT 0,
    prs              INT            NOT NULL DEFAULT 0,
    issues           INT            NOT NULL DEFAULT 0,
    total_score      DECIMAL(10, 2) NOT NULL DEFAULT 0,
    main_repo_score  DECIMAL(10, 2) NOT NULL DEFAULT 0,
    other_repo_score DECIMAL(10, 2) NOT NULL DEFAULT 0,
    pr_issue_score   DECIMAL(10, 2) NOT NULL DEFAULT 0,
    reputation_score DECIMAL(10, 2) NOT NULL DEFAULT 0,
    rank             INT,
    percentile       INT,
    best_repo_owner  VARCHAR(100),
    best_repo_name   VARCHAR(200),
    best_repo_commits INT,
    calculated_at    TIMESTAMP      NOT NULL,
    CONSTRAINT pk_github_yearly_statistics PRIMARY KEY (id),
    CONSTRAINT uk_github_id_year UNIQUE (github_id, year)
);

CREATE INDEX idx_gys_github_id ON github_yearly_statistics (github_id);
CREATE INDEX idx_gys_year ON github_yearly_statistics (year);
CREATE INDEX idx_gys_total_score ON github_yearly_statistics (total_score DESC);

CREATE TABLE github_contribution_pattern (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    github_id           VARCHAR(100) NOT NULL UNIQUE,
    night_owl_score     INT          NOT NULL DEFAULT 0,
    night_commits       INT          NOT NULL DEFAULT 0,
    day_commits         INT          NOT NULL DEFAULT 0,
    initiator_score     INT          NOT NULL DEFAULT 0,
    early_contributions INT          NOT NULL DEFAULT 0,
    independent_score   INT          NOT NULL DEFAULT 0,
    solo_projects       INT          NOT NULL DEFAULT 0,
    total_projects      INT          NOT NULL DEFAULT 0,
    total_coworkers     INT          NOT NULL DEFAULT 0,
    hourly_distribution TEXT,
    calculated_at       TIMESTAMP    NOT NULL,
    CONSTRAINT pk_github_contribution_pattern PRIMARY KEY (id)
);

CREATE INDEX idx_gcp_github_id ON github_contribution_pattern (github_id);

CREATE TABLE github_global_statistics (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    avg_commit_count DOUBLE PRECISION NOT NULL DEFAULT 0,
    avg_star_count   DOUBLE PRECISION NOT NULL DEFAULT 0,
    avg_pr_count     DOUBLE PRECISION NOT NULL DEFAULT 0,
    avg_issue_count  DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_users      INT              NOT NULL DEFAULT 0,
    calculated_at    TIMESTAMP        NOT NULL,
    CONSTRAINT pk_github_global_statistics PRIMARY KEY (id)
);

CREATE INDEX idx_ggs_calculated_at ON github_global_statistics (calculated_at);

CREATE TABLE platform_statistics (
    stat_key         VARCHAR(50) PRIMARY KEY,
    avg_commit_count DECIMAL(15, 2) NOT NULL DEFAULT 0,
    avg_star_count   DECIMAL(15, 2) NOT NULL DEFAULT 0,
    avg_pr_count     DECIMAL(15, 2) NOT NULL DEFAULT 0,
    avg_issue_count  DECIMAL(15, 2) NOT NULL DEFAULT 0,
    total_user_count INT            NOT NULL DEFAULT 0,
    calculated_at    TIMESTAMP      NOT NULL
);

INSERT INTO platform_statistics (stat_key, avg_commit_count, avg_star_count, avg_pr_count, avg_issue_count, total_user_count, calculated_at)
VALUES ('global', 0, 0, 0, 0, 0, CURRENT_TIMESTAMP);

-- ============================================
-- Spring Batch Tables (for Harvester)
-- ============================================

CREATE TABLE batch_job_instance (
    job_instance_id BIGINT       NOT NULL PRIMARY KEY,
    version         BIGINT,
    job_name        VARCHAR(100) NOT NULL,
    job_key         VARCHAR(32)  NOT NULL,
    CONSTRAINT job_inst_un UNIQUE (job_name, job_key)
);

CREATE TABLE batch_job_execution (
    job_execution_id BIGINT    NOT NULL PRIMARY KEY,
    version          BIGINT,
    job_instance_id  BIGINT    NOT NULL,
    create_time      TIMESTAMP NOT NULL,
    start_time       TIMESTAMP,
    end_time         TIMESTAMP,
    status           VARCHAR(10),
    exit_code        VARCHAR(2500),
    exit_message     VARCHAR(2500),
    last_updated     TIMESTAMP,
    CONSTRAINT job_inst_exec_fk FOREIGN KEY (job_instance_id) REFERENCES batch_job_instance(job_instance_id)
);

CREATE TABLE batch_job_execution_params (
    job_execution_id BIGINT       NOT NULL,
    parameter_name   VARCHAR(100) NOT NULL,
    parameter_type   VARCHAR(100) NOT NULL,
    parameter_value  VARCHAR(2500),
    identifying      CHAR(1)      NOT NULL,
    CONSTRAINT job_exec_params_fk FOREIGN KEY (job_execution_id) REFERENCES batch_job_execution(job_execution_id)
);

CREATE TABLE batch_step_execution (
    step_execution_id  BIGINT       NOT NULL PRIMARY KEY,
    version            BIGINT       NOT NULL,
    step_name          VARCHAR(100) NOT NULL,
    job_execution_id   BIGINT       NOT NULL,
    create_time        TIMESTAMP    NOT NULL,
    start_time         TIMESTAMP,
    end_time           TIMESTAMP,
    status             VARCHAR(10),
    commit_count       BIGINT,
    read_count         BIGINT,
    filter_count       BIGINT,
    write_count        BIGINT,
    read_skip_count    BIGINT,
    write_skip_count   BIGINT,
    process_skip_count BIGINT,
    rollback_count     BIGINT,
    exit_code          VARCHAR(2500),
    exit_message       VARCHAR(2500),
    last_updated       TIMESTAMP,
    CONSTRAINT job_exec_step_fk FOREIGN KEY (job_execution_id) REFERENCES batch_job_execution(job_execution_id)
);

CREATE TABLE batch_step_execution_context (
    step_execution_id  BIGINT        NOT NULL PRIMARY KEY,
    short_context      VARCHAR(2500) NOT NULL,
    serialized_context TEXT,
    CONSTRAINT step_exec_ctx_fk FOREIGN KEY (step_execution_id) REFERENCES batch_step_execution(step_execution_id)
);

CREATE TABLE batch_job_execution_context (
    job_execution_id   BIGINT        NOT NULL PRIMARY KEY,
    short_context      VARCHAR(2500) NOT NULL,
    serialized_context TEXT,
    CONSTRAINT job_exec_ctx_fk FOREIGN KEY (job_execution_id) REFERENCES batch_job_execution(job_execution_id)
);

CREATE SEQUENCE batch_step_execution_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE batch_job_execution_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE batch_job_seq START WITH 1 INCREMENT BY 1;
