-- 미가입자 팀 초대(대기) 테이블.
-- 아직 K-OSP에 가입하지 않은 코리아텍 이메일 사용자를 팀에 초대할 때 사용한다.
-- 초대받은 사람이 해당 이메일로 회원가입을 완료하면 실제 team_invite 로 전환된다.
CREATE TABLE pending_team_invite
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    team_id    BIGINT       NOT NULL,
    inviter_id BIGINT       NOT NULL,
    email      VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    is_deleted BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_pending_team_invite PRIMARY KEY (id),
    CONSTRAINT uk_pending_team_invite_team_email UNIQUE (team_id, email),
    CONSTRAINT fk_pending_team_invite_on_team FOREIGN KEY (team_id) REFERENCES team (id),
    CONSTRAINT fk_pending_team_invite_on_inviter FOREIGN KEY (inviter_id) REFERENCES users (id)
);

CREATE INDEX idx_pending_team_invite_email ON pending_team_invite (email) WHERE is_deleted = FALSE;
