-- ============================================
-- Learning Material System (학습자료)
-- 아우누리 과제 / EL 자료 / GitHub / 수동 업로드 자료를
-- 연도·학기·과목 폴더 계층으로 관리하고 폴더별 공개/비공개를 지원한다.
-- 파일 실체는 기존 S3 업로드(attachment)와 별개로 material_item에 메타데이터로 보관하며,
-- 향후 연동을 위해 attachment_id 참조를 nullable 로 둔다.
-- ============================================

-- 폴더 (연도 > 학기 > 과목 > 커스텀 계층)
CREATE TABLE material_folder
(
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    user_id         BIGINT       NOT NULL,
    parent_id       BIGINT,
    name            VARCHAR(255) NOT NULL,
    folder_type     VARCHAR(20)  NOT NULL DEFAULT 'CUSTOM',   -- YEAR / SEMESTER / SUBJECT / CUSTOM
    source          VARCHAR(30)  NOT NULL DEFAULT 'MANUAL',    -- AUNURI_ASSIGNMENT / AUNURI_EL / GITHUB / MANUAL
    visibility      VARCHAR(10)  NOT NULL DEFAULT 'PRIVATE',   -- PUBLIC / PRIVATE
    is_start_folder BOOLEAN      NOT NULL DEFAULT FALSE,       -- 첨부파일 페이지 진입 기본 폴더
    sort_order      INT          NOT NULL DEFAULT 0,
    CONSTRAINT pk_material_folder PRIMARY KEY (id),
    CONSTRAINT fk_material_folder_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_material_folder_parent FOREIGN KEY (parent_id) REFERENCES material_folder (id)
);

CREATE INDEX idx_material_folder_user ON material_folder (user_id);
CREATE INDEX idx_material_folder_parent ON material_folder (parent_id);
CREATE INDEX idx_material_folder_user_visibility ON material_folder (user_id, visibility);

-- 개별 자료 (과제/EL 자료 1건)
CREATE TABLE material_item
(
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL,
    folder_id          BIGINT       NOT NULL,
    user_id            BIGINT       NOT NULL,
    title              VARCHAR(255) NOT NULL,
    subject_name       VARCHAR(255),
    material_year      INT,
    semester           VARCHAR(20),
    source             VARCHAR(30)  NOT NULL DEFAULT 'MANUAL', -- AUNURI_ASSIGNMENT / AUNURI_EL / GITHUB / MANUAL
    source_url         VARCHAR(500),                            -- 아우누리 원본 링크
    attachment_id      BIGINT,                                  -- 기존 attachment 테이블 참조(옵션)
    file_url           VARCHAR(500),                            -- 업로드된 파일 URL(S3)
    original_file_name VARCHAR(255),
    file_size          BIGINT,
    content_type       VARCHAR(100),
    visibility         VARCHAR(10),                             -- 아이템 단위 override(NULL 이면 폴더 공개설정 상속)
    material_date      TIMESTAMP,                               -- 원본 게시/제출일(최신순 정렬 기준)
    CONSTRAINT pk_material_item PRIMARY KEY (id),
    CONSTRAINT fk_material_item_folder FOREIGN KEY (folder_id) REFERENCES material_folder (id),
    CONSTRAINT fk_material_item_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_material_item_attachment FOREIGN KEY (attachment_id) REFERENCES attachment (id)
);

CREATE INDEX idx_material_item_folder ON material_item (folder_id);
CREATE INDEX idx_material_item_user ON material_item (user_id);
CREATE INDEX idx_material_item_user_date ON material_item (user_id, material_date DESC);
