-- ============================================
-- Follow System (팔로잉/팔로워)
-- 사용자 간 단방향 팔로우 관계.
-- follower_id 가 following_id 를 팔로우한다.
-- ============================================

CREATE TABLE follow
(
    id           BIGINT    GENERATED BY DEFAULT AS IDENTITY,
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL,
    follower_id  BIGINT    NOT NULL,
    following_id BIGINT    NOT NULL,
    CONSTRAINT pk_follow PRIMARY KEY (id),
    CONSTRAINT uc_follow_follower_following UNIQUE (follower_id, following_id),
    CONSTRAINT fk_follow_follower FOREIGN KEY (follower_id) REFERENCES users (id),
    CONSTRAINT fk_follow_following FOREIGN KEY (following_id) REFERENCES users (id)
);

CREATE INDEX idx_follow_follower ON follow (follower_id);
CREATE INDEX idx_follow_following ON follow (following_id);
