-- ============================================
-- Title System Tables
-- ============================================

-- 칭호 마스터 테이블
CREATE TABLE title
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    name          VARCHAR(50)  NOT NULL,
    description   VARCHAR(255) NOT NULL,
    category      VARCHAR(30)  NOT NULL,
    rarity        VARCHAR(20)  NOT NULL DEFAULT 'COMMON',
    icon_url      VARCHAR(500),
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INT          NOT NULL DEFAULT 0,
    CONSTRAINT pk_title PRIMARY KEY (id),
    CONSTRAINT uc_title_name UNIQUE (name)
);

CREATE INDEX idx_title_category ON title (category);
CREATE INDEX idx_title_is_active ON title (is_active);
CREATE INDEX idx_title_display_order ON title (display_order);

-- 칭호 조건 테이블 (1 title : N conditions, AND 로직)
CREATE TABLE title_condition
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    title_id        BIGINT       NOT NULL,
    condition_type  VARCHAR(50)  NOT NULL,
    threshold_value INT          NOT NULL DEFAULT 0,
    description     VARCHAR(255),
    CONSTRAINT pk_title_condition PRIMARY KEY (id),
    CONSTRAINT fk_title_condition_on_title FOREIGN KEY (title_id) REFERENCES title (id)
);

CREATE INDEX idx_title_condition_title_id ON title_condition (title_id);
CREATE INDEX idx_title_condition_type ON title_condition (condition_type);

-- 유저 칭호 보유 테이블
CREATE TABLE user_title
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    user_id      BIGINT       NOT NULL,
    title_id     BIGINT       NOT NULL,
    is_display   BOOLEAN      NOT NULL DEFAULT FALSE,
    grant_source VARCHAR(20)  NOT NULL DEFAULT 'SYSTEM',
    granted_at   TIMESTAMP    NOT NULL,
    is_revoked   BOOLEAN      NOT NULL DEFAULT FALSE,
    revoked_at   TIMESTAMP,
    revoked_by   BIGINT,
    CONSTRAINT pk_user_title PRIMARY KEY (id),
    CONSTRAINT fk_user_title_on_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_title_on_title FOREIGN KEY (title_id) REFERENCES title (id)
);

CREATE INDEX idx_user_title_user_id ON user_title (user_id);
CREATE INDEX idx_user_title_title_id ON user_title (title_id);
CREATE INDEX idx_user_title_user_display ON user_title (user_id, is_display);
-- 유저당 활성 칭호 중복 지급 방지를 위한 partial unique index
CREATE UNIQUE INDEX uidx_user_title_active ON user_title (user_id, title_id) WHERE is_revoked = FALSE;

-- 유저 로그인 연속 접속 테이블
CREATE TABLE user_login_streak
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP NOT NULL,
    user_id          BIGINT    NOT NULL,
    current_streak   INT       NOT NULL DEFAULT 0,
    longest_streak   INT       NOT NULL DEFAULT 0,
    last_login_date  DATE,
    CONSTRAINT pk_user_login_streak PRIMARY KEY (id),
    CONSTRAINT uc_user_login_streak_user UNIQUE (user_id),
    CONSTRAINT fk_user_login_streak_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_user_login_streak_user_id ON user_login_streak (user_id);

-- 칭호 배치 실행 로그 테이블
CREATE TABLE title_batch_log
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at           TIMESTAMP    NOT NULL,
    updated_at           TIMESTAMP    NOT NULL,
    executed_at          TIMESTAMP    NOT NULL,
    finished_at          TIMESTAMP,
    status               VARCHAR(20)  NOT NULL DEFAULT 'RUNNING',
    processed_user_count INT          NOT NULL DEFAULT 0,
    granted_title_count  INT          NOT NULL DEFAULT 0,
    error_message        TEXT,
    CONSTRAINT pk_title_batch_log PRIMARY KEY (id)
);

CREATE INDEX idx_title_batch_log_status ON title_batch_log (status);
CREATE INDEX idx_title_batch_log_executed_at ON title_batch_log (executed_at DESC);

-- 관리자 칭호 수동 지급/회수 로그 테이블
CREATE TABLE title_admin_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    admin_id   BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    title_id   BIGINT       NOT NULL,
    action     VARCHAR(20)  NOT NULL,
    reason     VARCHAR(500) NOT NULL,
    CONSTRAINT pk_title_admin_log PRIMARY KEY (id),
    CONSTRAINT fk_title_admin_log_on_title FOREIGN KEY (title_id) REFERENCES title (id)
);

CREATE INDEX idx_title_admin_log_admin_id ON title_admin_log (admin_id);
CREATE INDEX idx_title_admin_log_user_id ON title_admin_log (user_id);
CREATE INDEX idx_title_admin_log_created_at ON title_admin_log (created_at DESC);
