-- ============================================
-- Season Ranking System Tables
-- ============================================

-- 시즌 테이블
CREATE TABLE season
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    name       VARCHAR(100) NOT NULL,
    start_date DATE         NOT NULL,
    end_date   DATE         NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_season PRIMARY KEY (id),
    CONSTRAINT uc_season_name UNIQUE (name)
);

CREATE INDEX idx_season_is_active ON season (is_active);

-- 시즌 점수 정책 테이블
CREATE TABLE season_score_policy
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    season_id       BIGINT       NOT NULL,
    score_type      VARCHAR(50)  NOT NULL,
    base_score      NUMERIC(8, 4) NOT NULL,
    max_daily_score NUMERIC(8, 4),
    extra_config    JSONB,
    CONSTRAINT pk_season_score_policy PRIMARY KEY (id),
    CONSTRAINT uc_season_policy UNIQUE (season_id, score_type),
    CONSTRAINT fk_season_score_policy_season FOREIGN KEY (season_id) REFERENCES season (id)
);

-- 시즌 랭킹 점수 집계 테이블
CREATE TABLE season_ranking_score
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at         TIMESTAMP     NOT NULL,
    updated_at         TIMESTAMP     NOT NULL,
    season_id          BIGINT        NOT NULL,
    user_id            BIGINT        NOT NULL,
    attendance_score   NUMERIC(8, 4) NOT NULL DEFAULT 0,
    commit_score       NUMERIC(8, 4) NOT NULL DEFAULT 0,
    challenge_score    NUMERIC(8, 4) NOT NULL DEFAULT 0,
    project_score      NUMERIC(8, 4) NOT NULL DEFAULT 0,
    community_score    NUMERIC(8, 4) NOT NULL DEFAULT 0,
    total_score        NUMERIC(8, 4) NOT NULL DEFAULT 0,
    tier               VARCHAR(20)   NOT NULL DEFAULT 'BRONZE_4',
    rank_in_season     INT,
    last_calculated_at TIMESTAMP,
    CONSTRAINT pk_season_ranking_score PRIMARY KEY (id),
    CONSTRAINT uc_season_user UNIQUE (season_id, user_id),
    CONSTRAINT fk_season_ranking_score_season FOREIGN KEY (season_id) REFERENCES season (id),
    CONSTRAINT fk_season_ranking_score_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_season_ranking_score_total ON season_ranking_score (season_id, total_score DESC);
CREATE INDEX idx_season_ranking_score_user ON season_ranking_score (user_id);

-- 시즌 점수 이벤트 로그 테이블 (감사 원장, append-only)
CREATE TABLE season_score_event_log
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at      TIMESTAMP     NOT NULL,
    season_id       BIGINT        NOT NULL,
    user_id         BIGINT        NOT NULL,
    event_type      VARCHAR(50)   NOT NULL,
    score_delta     NUMERIC(8, 4) NOT NULL,
    source_ref_id   BIGINT,
    source_ref_type VARCHAR(50),
    description     VARCHAR(255),
    event_date      DATE          NOT NULL,
    CONSTRAINT pk_season_score_event_log PRIMARY KEY (id),
    CONSTRAINT fk_season_score_event_log_season FOREIGN KEY (season_id) REFERENCES season (id),
    CONSTRAINT fk_season_score_event_log_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_score_event_log_user_date ON season_score_event_log (season_id, user_id, event_date);
CREATE INDEX idx_score_event_log_type_date ON season_score_event_log (season_id, event_type, event_date);

-- 시즌 종료 스냅샷 테이블 (불변 기록)
CREATE TABLE season_ranking_snapshot
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP     NOT NULL,
    season_id   BIGINT        NOT NULL,
    user_id     BIGINT        NOT NULL,
    final_score NUMERIC(8, 4) NOT NULL,
    final_tier  VARCHAR(20)   NOT NULL,
    final_rank  INT           NOT NULL,
    snapshot_at TIMESTAMP     NOT NULL,
    CONSTRAINT pk_season_ranking_snapshot PRIMARY KEY (id),
    CONSTRAINT uc_snapshot UNIQUE (season_id, user_id),
    CONSTRAINT fk_season_ranking_snapshot_season FOREIGN KEY (season_id) REFERENCES season (id),
    CONSTRAINT fk_season_ranking_snapshot_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_season_ranking_snapshot_season ON season_ranking_snapshot (season_id, final_rank);

-- 시즌 프로젝트 테이블 (관리자 오픈/클로즈)
CREATE TABLE season_project
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    season_id     BIGINT       NOT NULL,
    name          VARCHAR(200) NOT NULL,
    project_level INT          NOT NULL CHECK (project_level BETWEEN 1 AND 5),
    status        VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    created_by    BIGINT       NOT NULL,
    closed_at     TIMESTAMP,
    note          VARCHAR(500),
    CONSTRAINT pk_season_project PRIMARY KEY (id),
    CONSTRAINT fk_season_project_season FOREIGN KEY (season_id) REFERENCES season (id),
    CONSTRAINT fk_season_project_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_season_project_season_id ON season_project (season_id);
CREATE INDEX idx_season_project_status ON season_project (status);

-- 시즌 프로젝트 참여자 테이블
CREATE TABLE season_project_member
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at   TIMESTAMP   NOT NULL,
    updated_at   TIMESTAMP   NOT NULL,
    project_id   BIGINT      NOT NULL,
    user_id      BIGINT      NOT NULL,
    role_type    VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    score_granted BOOLEAN    NOT NULL DEFAULT FALSE,
    granted_at   TIMESTAMP,
    CONSTRAINT pk_season_project_member PRIMARY KEY (id),
    CONSTRAINT uc_project_member UNIQUE (project_id, user_id),
    CONSTRAINT fk_season_project_member_project FOREIGN KEY (project_id) REFERENCES season_project (id),
    CONSTRAINT fk_season_project_member_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_season_project_member_project_id ON season_project_member (project_id);
CREATE INDEX idx_season_project_member_user_id ON season_project_member (user_id);
