-- ============================================
-- Terms System Tables
-- ============================================

-- 약관 문서 테이블
CREATE TABLE terms
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    version    VARCHAR(20)  NOT NULL,
    content    TEXT         NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_terms PRIMARY KEY (id),
    CONSTRAINT uc_terms_version UNIQUE (version)
);

CREATE INDEX idx_terms_is_active ON terms (is_active);

-- 사용자 약관 동의 이력 테이블
CREATE TABLE user_terms_agreement
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    user_id    BIGINT    NOT NULL,
    terms_id   BIGINT    NOT NULL,
    agreed_at  TIMESTAMP NOT NULL,
    CONSTRAINT pk_user_terms_agreement PRIMARY KEY (id),
    CONSTRAINT uc_user_terms UNIQUE (user_id, terms_id),
    CONSTRAINT fk_user_terms_agreement_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_terms_agreement_terms FOREIGN KEY (terms_id) REFERENCES terms (id)
);

CREATE INDEX idx_user_terms_agreement_user_id ON user_terms_agreement (user_id);
