CREATE TABLE processed_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id      VARCHAR(255) NOT NULL UNIQUE,
    event_type      VARCHAR(255) NOT NULL,
    processed_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_processed_messages PRIMARY KEY (id)
);

CREATE INDEX idx_message_id ON processed_messages(message_id);
